In [1]:
import numpy
numpy.set_printoptions(sign=' ')
A = numpy.array(list(map(float, input().split())), dtype=float)
print (numpy.floor(A))
print (numpy.ceil(A))
print (numpy.rint(A))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]
