Task

You are given a space separated list of nine integers. Your task is to convert this list into a 3X3 NumPy array.

In [3]:
import numpy


my_array=input().split()
my_array1=numpy.array(my_array,int)
print(numpy.reshape(my_array1,(3,3)))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
